# PistonLimits plugin config - 1.0
# Messages
messages:
  reload_success: "&dPistonLimits &econfiguration reloaded &asuccessfully&e."
  no_permission: "&cYou do not have permission to use this command."

# Blocks limited from being pushed by pistons, they must be added in all caps.
# You can also add "*" in order to block all blocks from being pushed by pistons.
# Piston and Sticky Piston have been added as an example, you can remove them if you want.
blocked-blocks:
#  - "*" # This blocks all blocks from being pushed by pistons, you can uncomment it for it to work.
  - PISTON
  - STICKY_PISTON

# End of config.